-- MySQL Script generated by MySQL Workbench
-- Sun Sep 20 16:30:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usairlineflights2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usairlineflights2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usairlineflights2` DEFAULT CHARACTER SET latin1 ;
USE `usairlineflights2` ;

-- -----------------------------------------------------
-- Table `usairlineflights2`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`airports` (
  `iata` VARCHAR(150) NOT NULL,
  `airport` TEXT NULL DEFAULT NULL,
  `city` TEXT NULL DEFAULT NULL,
  `state` TEXT NULL DEFAULT NULL,
  `country` TEXT NULL DEFAULT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `long` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`iata`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `usairlineflights2`.`carriers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`carriers` (
  `Code` VARCHAR(150) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `usairlineflights2`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`flights` (
  `FlightNum` INT(250) NOT NULL,
  `UniqueCarrier` VARCHAR(150) NOT NULL,
  `Origin` VARCHAR(150) NOT NULL,
  `Dest` VARCHAR(150) NOT NULL,
  `colYear` INT(11) NULL DEFAULT NULL,
  `colMonth` INT(11) NULL DEFAULT NULL,
  `DayOfMonths` INT(11) NULL DEFAULT NULL,
  `DayOfWeek` INT(11) NULL DEFAULT NULL,
  `DepTime` INT(11) NULL DEFAULT NULL,
  `CRSDepTime` INT(11) NULL DEFAULT NULL,
  `ArrTime` INT(11) NULL DEFAULT NULL,
  `CRSArrTime` INT(11) NULL DEFAULT NULL,
  `TailNum` TEXT NULL DEFAULT NULL,
  `ActualElapsedTime` INT(11) NULL DEFAULT NULL,
  `CRSElapsedTime` INT(11) NULL DEFAULT NULL,
  `AirTime` INT(11) NULL DEFAULT NULL,
  `ArrDelay` INT(11) NULL DEFAULT NULL,
  `DepDelay` INT(11) NULL DEFAULT NULL,
  `Distance` INT(11) NULL DEFAULT NULL,
  `TaxiIn` INT(11) NULL DEFAULT NULL,
  `TaxiOut` INT(11) NULL DEFAULT NULL,
  `Cancelled` INT(11) NULL DEFAULT NULL,
  `CancellationCode` TEXT NULL DEFAULT NULL,
  `Diverted` INT(11) NULL DEFAULT NULL,
  `CarrierDelay` INT(11) NULL DEFAULT NULL,
  `WeatherDelay` INT(11) NULL DEFAULT NULL,
  `NASDelay` INT(11) NULL DEFAULT NULL,
  `SecurityDelay` INT(11) NULL DEFAULT NULL,
  `LateAircraftDelay` INT(11) NULL DEFAULT NULL,
  `flightscol` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
